# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-28 15:26
from __future__ import unicode_literals

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import staff.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=10, unique=True, verbose_name='學號')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('M', '男生'), ('F', '女生')], max_length=1, verbose_name='性別')),
                ('birthday', models.DateField(default=django.utils.timezone.now, verbose_name='出生年月日')),
                ('idno', models.CharField(max_length=10, verbose_name='身份證字號')),
                ('role', models.CharField(blank=True, choices=[('就輔組', '就輔組'), ('行政組 - 總召', '行政組 - 總召'), ('行政組 - 副召', '行政組 - 副召'), ('行政組 - 執秘', '行政組 - 執秘'), ('廠聯組 - 組長', '廠聯組 - 組長'), ('廠聯組 - 組員', '廠聯組 - 組員'), ('設計組 - 組長', '設計組 - 組長'), ('設計組 - 組員', '設計組 - 組員'), ('活動組 - 組長', '活動組 - 組長'), ('活動組 - 組員', '活動組 - 組員'), ('資訊組 - 組長', '資訊組 - 組長'), ('資訊組 - 組員', '資訊組 - 組員'), ('專刊組 - 組長', '專刊組 - 組長'), ('專刊組 - 組員', '專刊組 - 組員')], max_length=10, verbose_name='職位')),
                ('mobile', models.CharField(help_text='格式: 0912-345678', max_length=12, validators=[staff.models.validate_mobile], verbose_name='手機')),
                ('email', models.CharField(max_length=64, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('fb_url', models.URLField(default='', verbose_name='FB個人首頁連結')),
                ('account', models.CharField(help_text='必需為自己的名字', max_length=15, verbose_name='郵局或玉山帳號')),
                ('last_update', models.DateTimeField(auto_now=True, null=True, verbose_name='更新時間')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='最高權限')),
                ('groups', models.ManyToManyField(blank=True, related_name='staff_groups', related_query_name='staff_groups', to='auth.Group')),
            ],
            options={
                'managed': True,
                'verbose_name': 'OpenHouse 工作人員',
                'verbose_name_plural': 'OpenHouse 工作人員',
                'db_table': 'staff',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
