# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-28 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20160428_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='username',
            field=models.CharField(max_length=10, unique=True, verbose_name='學號/帳號'),
        ),
    ]
