# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 12:14
from __future__ import unicode_literals

import company.models
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cid', models.CharField(max_length=8, unique=True, verbose_name='公司統一編號')),
                ('name', models.CharField(max_length=64, verbose_name='公司名稱')),
                ('shortname', models.CharField(max_length=20, verbose_name='公司簡稱')),
                ('category', models.CharField(choices=[('半導體', '半導體'), ('消費電子', '消費電子'), ('網路通訊', '網路通訊'), ('光電光學', '光電光學'), ('資訊軟體', '資訊軟體'), ('集團', '集團'), ('綜合', '綜合'), ('人力銀行', '人力銀行'), ('機構', '機構')], max_length=37, verbose_name='類別')),
                ('phone', models.CharField(help_text='格式: 區碼-號碼#分機', max_length=32, validators=[company.models.validate_phone], verbose_name='公司電話')),
                ('postal_code', models.CharField(max_length=5, validators=[company.models.validate_all_num], verbose_name='郵遞區號')),
                ('address', models.CharField(max_length=128, verbose_name='公司地址')),
                ('website', models.CharField(max_length=64, verbose_name='公司網站')),
                ('brief', models.CharField(max_length=110, verbose_name='公司介紹')),
                ('introduction', models.CharField(max_length=260, verbose_name='公司簡介')),
                ('hr_name', models.CharField(max_length=32, verbose_name='人資姓名')),
                ('hr_phone', models.CharField(help_text='格式: 區碼-號碼#分機', max_length=32, validators=[company.models.validate_phone], verbose_name='人資電話')),
                ('hr_fax', models.CharField(help_text='格式: 區碼-號碼#分機', max_length=32, verbose_name='人資傳真')),
                ('hr_mobile', models.CharField(help_text='格式: 0912-345678', max_length=32, validators=[company.models.validate_mobile], verbose_name='人資手機')),
                ('hr_email', models.CharField(max_length=64, validators=[django.core.validators.EmailValidator()], verbose_name='人資Email')),
                ('logo', models.ImageField(help_text='網站展示、筆記本內頁公司介紹使用，僅接受 jpg, png, gif 格式。建議解析度為 300 dpi以上，以達到最佳效果。', null=True, upload_to='logos', verbose_name='公司LOGO')),
                ('last_update', models.DateTimeField(auto_now=True, null=True, verbose_name='更新時間')),
                ('abroad', models.TextField(blank=True, null=True)),
                ('date_join', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
            ],
            options={
                'verbose_name': '廠商',
                'db_table': 'company',
                'verbose_name_plural': '廠商',
                'managed': True,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
