# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-28 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(help_text='網站展示、筆記本內頁公司介紹使用，僅接受 jpg, png, gif 格式。建議解析度為 300 dpi以上，以達到最佳效果。', null=True, upload_to='company_logos', verbose_name='公司LOGO'),
        ),
    ]
