# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-28 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20160428_2215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'managed': True, 'verbose_name': '總廠商列表', 'verbose_name_plural': '總廠商列表'},
        ),
    ]
